import type { Product } from "./types"

export const mockProducts: Product[] = [
  {
    id: "1",
    name: "Leche Entera 1L",
    price: 1.2,
    stock: 150,
    category: "Leche",
  },
  {
    id: "2",
    name: "Leche Descremada 1L",
    price: 1.3,
    stock: 120,
    category: "Leche",
  },
  {
    id: "3",
    name: "Yogurt Natural 500g",
    price: 2.5,
    stock: 80,
    category: "Yogurt",
  },
  {
    id: "4",
    name: "Yogurt Frutilla 500g",
    price: 2.75,
    stock: 65,
    category: "Yogurt",
  },
  {
    id: "5",
    name: "Queso Fresco 250g",
    price: 3.2,
    stock: 45,
    category: "Queso",
  },
  {
    id: "6",
    name: "Queso Mozzarella 500g",
    price: 4.5,
    stock: 30,
    category: "Queso",
  },
  {
    id: "7",
    name: "Mantequilla 200g",
    price: 2.8,
    stock: 55,
    category: "Mantequilla",
  },
  {
    id: "8",
    name: "Crema de Leche 250ml",
    price: 1.9,
    stock: 70,
    category: "Crema",
  },
  {
    id: "9",
    name: "Dulce de Leche 400g",
    price: 3.1,
    stock: 40,
    category: "Dulce",
  },
  {
    id: "10",
    name: "Leche Condensada 395g",
    price: 2.95,
    stock: 35,
    category: "Leche",
  },
  {
    id: "11",
    name: "Queso Parmesano Rallado 100g",
    price: 3.75,
    stock: 25,
    category: "Queso",
  },
  {
    id: "12",
    name: "Yogurt Bebible Durazno 1L",
    price: 3.25,
    stock: 60,
    category: "Yogurt",
  },
  {
    id: "13",
    name: "Leche Chocolatada 1L",
    price: 1.85,
    stock: 90,
    category: "Leche",
  },
  {
    id: "14",
    name: "Queso Crema 300g",
    price: 2.6,
    stock: 50,
    category: "Queso",
  },
  {
    id: "15",
    name: "Mantequilla Sin Sal 200g",
    price: 2.9,
    stock: 45,
    category: "Mantequilla",
  },
]
